/**
 * Integration Service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { OEE } from "../../presentation/integration/oee";

export interface MachineOEE { 
    timeSeriesQueries?: Array<string>;
    start?: Date;
    end?: Date;
    isRelative?: boolean;
    response?: Array<MachineOEEDetails>;
}

export interface MachineOEEDetails { 
    machinePath?: string;
    machineName?: string;
    oee?: OEE;
}
